#!/usr/bin/env python
import socket               # Import socket module
import sys
import datetime


s = socket.socket()         # Create a socket object
#host = socket.gethostname() # Get local machine name

host = "192.168.60.150"
port = 12345                 # Reserve a port for your service.

s.connect((host, port))
PUT = "PUT"
s.send(PUT)
firstresult = s.recv(1024)
if not firstresult:
    exit(0)

if len(sys.argv) > 1:
    s.send(sys.argv[1]) 
else:
    now = datetime.datetime.now()
    now1 = now.strftime("%d%b%Y-%H:%M") 
    s.send(now1)
e = s.recv(1024)
print(e)
#f = open('tosend.png','rb')
f = sys.stdin
print 'Sending...'
l = f.read(1024)
#print(">>"l)
while (l):
    print 'Sending...'
    s.send(l)
    #e = s.recv(1204)
    #print("##"+ e)
    l = f.read(1024)
f.close()
print "Done Sending"
s.shutdown(socket.SHUT_WR)
print s.recv(1024)
s.close  
